# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: BazelTest

on: [push, workflow_dispatch]

jobs:
  bazel_test:
    strategy:
      matrix:
        # TODO: b/365609306 - Enable macos-latest and windows-latest runners.
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # gmock wants libtinfo5 which is not preinstalled on the ubuntu-latest GitHub Actions runner
    # (and as of the latest version, not available in the package manager).
    - if: matrix.os == 'ubuntu-latest'
      run: |
        wget https://mirrors.kernel.org/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
        echo "f04c382f877c9eab631818eadbfaa0c5 libtinfo5_6.3-2ubuntu0.1_amd64.deb" | md5sum -c --status
        sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb

    - name: Test
      run: bazel test --test_output=errors --keep_going //ink/...
